---
title: "In-Depth Statistical Analysis of Loan Default Dataset using tidymodels"
author: "Chris Olande"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: show
    theme: flatly
    highlight: tango
    fig_width: 10
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center",
  out.width = "100%"
)
```

```{r}
librarian::shelf(tidyverse, tidymodels, DataExplorer, GGally, corrplot, plotly, viridis,
pROC, randomForest, factoextra, cluster, ggthemes, ggridges, scales, vcd, kableExtra, DT, 
MASS, Rtsne, tsne, umap, conflicted, skimr)
```

```{r}
# Set custom theme

theme_custom <- function() {
  theme_minimal() +
    theme(
      plot.background = element_rect(fill = "white", color = NA),
      panel.grid.major = element_line(color = "gray90"),
      panel.grid.minor = element_blank(),
      plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = element_text(size = 12, color = "gray30", hjust = 0.5),
      axis.title = element_text(size = 12, face = "bold"),
      axis.text = element_text(size = 10),
      legend.title = element_text(size = 12, face = "bold"),
      legend.text = element_text(size = 10),
      legend.position = "right"
    )
}

theme_set(theme_custom())

```

```{r}
conflicted::conflicts_prefer(dplyr::select)
tidymodels_prefer()
```


```{r}
loan_data <- read_csv("dataset/Loan_Default.csv")
```


```{r}
# Remove the ID and Year column, the year is only filled with 2019
loan_data %>% 
  janitor::clean_names() %>% 
  select(-c(id, year)) -> loan_data
```


```{r}
# Select 20000 observations while maintaining the distribution in the target variable
# for fast modelling and visualization before upscaling
library(caTools)
set.seed(42)

split_ratio <- 20000 / nrow(loan_data)
split_index <- sample.split(loan_data$status, SplitRatio = split_ratio)

# Extract the sample
data <- loan_data[split_index, ]

```

```{r}
# Verify if the distribution is maintained
table(loan_data$status) / nrow(loan_data)
table(data$status) / nrow(data)
```


```{r}
cat("Dimensions of the loan_dataset", dim(data)[1], "rows and ", dim(data)[2], " columns")
head(data)
```


```{r}
# Obtain the summary statistics of the reduced dataset
skim(data) %>% 
  as.tibble() %>% 
  kable(caption = "Summary Statistics of the Loan Default data") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


```{r}
#Convert all character variables to factors
data <- data %>% 
  mutate_if(is.character, as.factor)

head(data)
```

## Missing data Analysis
```{r, fig.height = 12, fig.width=12}
plot_missing(data, missing_only = TRUE, title = "Missing Values Bar Chart") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(face = "bold"))
```


```{r}
# The missing values in upfront charges are as high as 5340 observations, we would like to knn impute them

data <- recipe(status ~ ., data) %>% 
  step_impute_knn(all_predictors()) %>% 
  prep() %>% 
  bake(new_data = NULL)
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

